#!/usr/bin/env bash
# cut_docs_snapshot.sh — congela la documentación actual como snapshot de una
# versión, para que el archivo publicado siga el ritmo de las releases.
#
# El sitio de la suite sirve SIEMPRE la doc actual bajo /orbit/, y los
# snapshots de las minors ya publicadas bajo su ruta de versión: es lo que
# permite a quien está clavado en una minor anterior leer la doc que le
# corresponde.
#
# A diferencia de quark y nucleus, orbit NO tiene instalación propia de
# Docusaurus (su website/ es solo docs/; el sitio lo ensambla el paraguas),
# así que aquí no se puede llamar a `docusaurus docs:version`. No hace falta:
# un snapshot son tres cosas mecánicas, y la sidebar de orbit es AUTOGENERADA
# desde la estructura de carpetas, así que la versionada es la misma
# declaración de una línea.
#
# Uso:
#   bash scripts/release/cut_docs_snapshot.sh            # versión del manifiesto
#   bash scripts/release/cut_docs_snapshot.sh 1.6.7      # explícita
#
# CUÁNDO: en el PR que precede al corte de una MINOR, y el ÚLTIMO de los
# cambios de documentación de la ronda — el snapshot es una copia byte a byte
# que se sirve para siempre bajo su ruta, así que un corte anterior a una
# corrección de prosa congela el texto equivocado y ningún guard lo ve (la
# copia archivada es coherente consigo misma).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

VERSION="${1:-$(python3 -c "import json;print(json.load(open('.release-please-manifest.json'))['.'])")}"

if ! printf '%s' "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
  echo "FAIL: versión inválida '$VERSION' (se espera X.Y.Z)" >&2
  exit 1
fi

DEST="website/versioned_docs/version-$VERSION"
if [ -d "$DEST" ]; then
  echo "OK: el snapshot $VERSION ya existe; nada que hacer."
  exit 0
fi

echo "Cortando snapshot de documentación $VERSION…"

mkdir -p website/versioned_docs website/versioned_sidebars
cp -R website/docs "$DEST"

# La sidebar de la instancia de orbit en el paraguas se llama `orbitSidebar` y
# es autogenerada desde la estructura de carpetas (el orden lo fija el
# `sidebar_position` del frontmatter). La versionada declara lo mismo sobre la
# carpeta del snapshot: nada que mantener a mano cuando se añade una página.
cat > "website/versioned_sidebars/version-$VERSION-sidebars.json" <<JSON
{
  "orbitSidebar": [
    {
      "type": "autogenerated",
      "dirName": "."
    }
  ]
}
JSON

python3 - "$VERSION" <<'PY'
import json, os, sys
version = sys.argv[1]
path = "website/versions.json"
versions = json.load(open(path)) if os.path.exists(path) else []
if version not in versions:
    versions.insert(0, version)
with open(path, "w") as fh:
    json.dump(versions, fh, indent=2)
    fh.write("\n")
print("versions.json:", ", ".join(versions))
PY

echo
echo "Hecho. Revisa y commitea:"
echo "  website/versions.json"
echo "  $DEST/"
echo "  website/versioned_sidebars/version-$VERSION-sidebars.json"
