// Copyright 2026 jcsvwinston/orbit
// SPDX-License-Identifier: Apache-2.0

package admin

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"sync"
	"time"
)

// The audit trail in the database.
//
// Until now the trail was an in-memory ring: it covered every mutating
// surface and recorded both sides of an edit, and none of it survived the
// process. That is the one question an incident asks — what happened before
// the restart — and a deploy, a crash or a second replica answered it with
// silence. Worse, it answered SILENTLY: the panel showed a trail, and the
// trail simply began when the process did.
//
// sqlAuditStore writes the same entries to a table the panel owns, in the
// same database the panel already authenticates against, and reads them back
// with the same filters. The ring stays: it is what a panel with no database
// handle gets, and what `audit_store: memory` selects deliberately.
//
// Failure discipline: an audit write must never fail the operation it
// records. A write that cannot reach the database is logged and kept in a
// small in-memory ring, so the panel keeps showing what it could not store
// instead of showing nothing.
const defaultAuditTable = "nucleus_admin_audit"

// auditFallbackSize is how many entries the SQL store keeps in memory when
// the database refuses them: enough to see the incident that is breaking the
// writes, not enough to be a second trail.
const auditFallbackSize = 200

type sqlAuditStore struct {
	db     *sql.DB
	table  string
	system string
	logger *slog.Logger

	// fallback holds entries the database refused, so a failed write is
	// visible in the panel rather than lost.
	fallback *auditStore

	// purgeMu guards the last-purge stamp, so retention runs at most once
	// per purgeInterval no matter how many writers ask for it.
	purgeMu   sync.Mutex
	lastPurge time.Time
}

func newSQLAuditStore(sqlDB *sql.DB, system string, logger *slog.Logger) *sqlAuditStore {
	return &sqlAuditStore{
		db:       sqlDB,
		table:    defaultAuditTable,
		system:   system,
		logger:   logger,
		fallback: newAuditStore(auditFallbackSize),
	}
}

func (s *sqlAuditStore) persistent() bool { return true }

// ensureSchema creates the audit table if it is not there. It runs once at
// mount, next to the admin-users bootstrap, and it is idempotent in every
// dialect.
func (s *sqlAuditStore) ensureSchema(ctx context.Context) error {
	if s == nil || s.db == nil {
		return fmt.Errorf("admin audit: nil sql db")
	}
	if _, err := s.db.ExecContext(ctx, auditTableDDL(s.system, s.table)); err != nil {
		return fmt.Errorf("admin audit: create table: %w", err)
	}
	// The index is what keeps the two reads the panel does — newest first,
	// and one record's history — from scanning the whole trail. A dialect
	// that refuses the statement is not a reason to run without a trail.
	for _, stmt := range auditIndexDDL(s.system, s.table) {
		if _, err := s.db.ExecContext(ctx, stmt); err != nil {
			if s.logger != nil {
				s.logger.Warn("admin audit: index not created", "error", err, "statement", stmt)
			}
		}
	}
	return nil
}

// auditTableDDL is the CREATE TABLE for the trail, in the dialect of system.
// It follows the discipline of bootstrapAdminUsersTableDDL — mssql has no
// IF NOT EXISTS and guards with OBJECT_ID, oracle wraps the create in a
// PL/SQL block that swallows ORA-00955 — and adds the one thing that table
// did not need: a key the DATABASE generates, so two replicas writing the
// same trail do not collide on it.
func auditTableDDL(system, table string) string {
	switch system {
	case "mssql":
		return fmt.Sprintf(`IF OBJECT_ID('%s', 'U') IS NULL
	CREATE TABLE %s (
		id BIGINT IDENTITY(1,1) PRIMARY KEY,
		user_id NVARCHAR(256) NULL,
		username NVARCHAR(256) NULL,
		action NVARCHAR(191) NOT NULL,
		model_name NVARCHAR(256) NULL,
		record_id NVARCHAR(256) NULL,
		old_value NVARCHAR(MAX) NULL,
		new_value NVARCHAR(MAX) NULL,
		ip NVARCHAR(256) NULL,
		user_agent NVARCHAR(512) NULL,
		created_at NVARCHAR(64) NOT NULL
	)`, table, table)
	case "oracle":
		return fmt.Sprintf(`BEGIN
	EXECUTE IMMEDIATE 'CREATE TABLE %s (
		id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		user_id VARCHAR2(256),
		username VARCHAR2(256),
		action VARCHAR2(191) NOT NULL,
		model_name VARCHAR2(256),
		record_id VARCHAR2(256),
		old_value CLOB,
		new_value CLOB,
		ip VARCHAR2(256),
		user_agent VARCHAR2(512),
		created_at VARCHAR2(64) NOT NULL
	)';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -955 THEN RAISE; END IF;
END;`, table)
	case "mysql":
		return fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	user_id VARCHAR(256),
	username VARCHAR(256),
	action VARCHAR(191) NOT NULL,
	model_name VARCHAR(256),
	record_id VARCHAR(256),
	old_value TEXT,
	new_value TEXT,
	ip VARCHAR(256),
	user_agent VARCHAR(512),
	created_at VARCHAR(64) NOT NULL
)`, table)
	case "postgresql", "postgres":
		return fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s (
	id BIGSERIAL PRIMARY KEY,
	user_id VARCHAR(256),
	username VARCHAR(256),
	action VARCHAR(191) NOT NULL,
	model_name VARCHAR(256),
	record_id VARCHAR(256),
	old_value TEXT,
	new_value TEXT,
	ip VARCHAR(256),
	user_agent VARCHAR(512),
	created_at VARCHAR(64) NOT NULL
)`, table)
	default: // sqlite, and the empty-system fallback
		return fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id TEXT,
	username TEXT,
	action TEXT NOT NULL,
	model_name TEXT,
	record_id TEXT,
	old_value TEXT,
	new_value TEXT,
	ip TEXT,
	user_agent TEXT,
	created_at TEXT NOT NULL
)`, table)
	}
}

// auditIndexDDL returns the index statements for the trail. Oracle and SQL
// Server have no CREATE INDEX IF NOT EXISTS, so their statements are the
// portable form and a second run is expected to fail harmlessly — which is
// why ensureSchema logs an index error instead of refusing to start.
func auditIndexDDL(system, table string) []string {
	switch system {
	case "mssql", "oracle":
		return []string{
			fmt.Sprintf("CREATE INDEX idx_%s_created ON %s (created_at)", table, table),
			fmt.Sprintf("CREATE INDEX idx_%s_record ON %s (model_name, record_id)", table, table),
		}
	default:
		return []string{
			fmt.Sprintf("CREATE INDEX IF NOT EXISTS idx_%s_created ON %s (created_at)", table, table),
			fmt.Sprintf("CREATE INDEX IF NOT EXISTS idx_%s_record ON %s (model_name, record_id)", table, table),
		}
	}
}

const auditColumns = "id, user_id, username, action, model_name, record_id, old_value, new_value, ip, user_agent, created_at"

// add writes one entry. It never returns an error and never blocks the
// operation it documents: a write the database refuses goes to the in-memory
// fallback and is logged.
func (s *sqlAuditStore) add(entry AuditEntry) {
	entry = boundAuditEntry(entry)
	entry.CreatedAt = time.Now().UTC()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	ph := bindPlaceholders(s.system, 10)
	if ph == nil {
		s.failed(entry, fmt.Errorf("unknown database dialect %q", s.system))
		return
	}
	stmt := fmt.Sprintf(
		"INSERT INTO %s (user_id, username, action, model_name, record_id, old_value, new_value, ip, user_agent, created_at) VALUES (%s)",
		s.table, strings.Join(ph, ", "))
	if _, err := s.db.ExecContext(ctx, stmt,
		entry.UserID, entry.Username, entry.Action, entry.ModelName, entry.RecordID,
		auditValueJSON(entry.OldValue), auditValueJSON(entry.NewValue),
		entry.IP, entry.UserAgent, entry.CreatedAt.Format(time.RFC3339Nano),
	); err != nil {
		s.failed(entry, err)
	}
}

// failed keeps an entry the database refused, so the panel shows it and the
// operator sees that the trail is degraded rather than quiet.
func (s *sqlAuditStore) failed(entry AuditEntry, err error) {
	if s.logger != nil {
		s.logger.Error("admin audit: entry not stored; keeping it in memory",
			"error", err, "action", entry.Action, "model", entry.ModelName)
	}
	s.fallback.add(entry)
}

// auditValueJSON renders a value map for storage. A value that cannot be
// marshalled is stored as an explicit marker rather than dropping the entry:
// the entry says WHO did WHAT, which matters more than its diff.
func auditValueJSON(v map[string]any) any {
	if v == nil {
		return nil
	}
	raw, err := json.Marshal(v)
	if err != nil {
		return `{"error":"value could not be encoded"}`
	}
	return string(raw)
}

// where builds the filter clause shared by list, count and the export.
func (s *sqlAuditStore) where(opts auditQueryOpts, from int) (string, []any) {
	var (
		clauses []string
		args    []any
	)
	add := func(column, value string) {
		if value == "" {
			return
		}
		ph := bindPlaceholders(s.system, from+len(args)+1)
		clauses = append(clauses, column+" = "+ph[len(ph)-1])
		args = append(args, value)
	}
	add("user_id", opts.UserID)
	add("model_name", opts.ModelName)
	add("record_id", opts.RecordID)
	add("action", opts.Action)
	if len(clauses) == 0 {
		return "", nil
	}
	return " WHERE " + strings.Join(clauses, " AND "), args
}

func (s *sqlAuditStore) list(opts auditQueryOpts) []AuditEntry {
	page, pageSize := normalizeAuditPage(opts.Page, opts.PageSize)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	where, args := s.where(opts, 0)
	// Ordering by id and not by created_at: the timestamp has whatever
	// resolution the driver stored, and two entries of the same millisecond
	// would tie — the ring never ties because ids are assigned in order, and
	// the table's key is assigned in order too.
	query := fmt.Sprintf("SELECT %s FROM %s%s ORDER BY id DESC", auditColumns, s.table, where)
	query += s.limitClause(pageSize, (page-1)*pageSize)

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		if s.logger != nil {
			s.logger.Error("admin audit: list failed", "error", err)
		}
		return s.fallback.list(opts)
	}
	defer func() { _ = rows.Close() }()

	// normalizeAuditPage has capped pageSize; the bound is repeated here as
	// an explicit guard so it is checkable where the allocation happens.
	capacity := pageSize
	if capacity > auditMaxPageSize {
		capacity = auditMaxPageSize
	}
	out := make([]AuditEntry, 0, capacity)
	for rows.Next() {
		entry, err := scanAuditRow(rows)
		if err != nil {
			if s.logger != nil {
				s.logger.Error("admin audit: scan failed", "error", err)
			}
			continue
		}
		out = append(out, entry)
	}
	return out
}

// limitClause is the dialect's way of saying "this page". Oracle and SQL
// Server want OFFSET … FETCH; the rest take LIMIT … OFFSET. The numbers are
// normalized ints, never client text.
func (s *sqlAuditStore) limitClause(limit, offset int) string {
	switch s.system {
	case "mssql", "oracle":
		return fmt.Sprintf(" OFFSET %d ROWS FETCH NEXT %d ROWS ONLY", offset, limit)
	default:
		return fmt.Sprintf(" LIMIT %d OFFSET %d", limit, offset)
	}
}

func scanAuditRow(rows *sql.Rows) (AuditEntry, error) {
	var (
		entry                          AuditEntry
		id                             int64
		userID, username, action       sql.NullString
		modelName, recordID            sql.NullString
		oldValue, newValue             any
		ip, userAgent, createdAtStored any
	)
	if err := rows.Scan(&id, &userID, &username, &action, &modelName, &recordID,
		&oldValue, &newValue, &ip, &userAgent, &createdAtStored); err != nil {
		return AuditEntry{}, err
	}
	entry.ID = uint(id)
	entry.UserID = userID.String
	entry.Username = username.String
	entry.Action = action.String
	entry.ModelName = modelName.String
	entry.RecordID = recordID.String
	entry.OldValue = decodeAuditValue(oldValue)
	entry.NewValue = decodeAuditValue(newValue)
	entry.IP = timestampText(ip)
	entry.UserAgent = timestampText(userAgent)
	entry.CreatedAt = parseAuditTime(createdAtStored)
	return entry, nil
}

// decodeAuditValue reads back a stored value map. Anything that is not valid
// JSON comes back as nil rather than as an error: a malformed diff must not
// hide the entry that carries it.
func decodeAuditValue(raw any) map[string]any {
	text := timestampText(raw)
	if strings.TrimSpace(text) == "" {
		return nil
	}
	var out map[string]any
	if err := json.Unmarshal([]byte(text), &out); err != nil {
		return nil
	}
	return out
}

// parseAuditTime reads the stored timestamp back, accepting what a driver
// may hand over: the RFC3339 text the panel wrote, or a real time value from
// a column somebody migrated to a timestamp type.
func parseAuditTime(raw any) time.Time {
	if t, ok := raw.(time.Time); ok {
		return t.UTC()
	}
	text := strings.TrimSpace(timestampText(raw))
	if text == "" {
		return time.Time{}
	}
	for _, layout := range []string{time.RFC3339Nano, time.RFC3339, "2006-01-02 15:04:05.999999999 -0700 MST", "2006-01-02 15:04:05"} {
		if t, err := time.Parse(layout, text); err == nil {
			return t.UTC()
		}
	}
	return time.Time{}
}

func (s *sqlAuditStore) count(opts auditQueryOpts) int {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	where, args := s.where(opts, 0)
	var n int64
	if err := s.db.QueryRowContext(ctx,
		fmt.Sprintf("SELECT COUNT(*) FROM %s%s", s.table, where), args...).Scan(&n); err != nil {
		if s.logger != nil {
			s.logger.Error("admin audit: count failed", "error", err)
		}
		return s.fallback.count(opts)
	}
	return int(n)
}

// clear empties the trail. It is the one operation that is destructive by
// design; the handler records who did it AFTER the wipe, so the table then
// holds exactly one entry saying so.
func (s *sqlAuditStore) clear() int {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	n := s.count(auditQueryOpts{})
	if _, err := s.db.ExecContext(ctx, fmt.Sprintf("DELETE FROM %s", s.table)); err != nil {
		if s.logger != nil {
			s.logger.Error("admin audit: clear failed", "error", err)
		}
		return 0
	}
	s.fallback.clear()
	return n
}

// purge drops every entry older than before — the retention policy, applied.
func (s *sqlAuditStore) purge(before time.Time) (int, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	ph := bindPlaceholders(s.system, 1)
	if ph == nil {
		return 0, fmt.Errorf("admin audit: unknown database dialect %q", s.system)
	}
	res, err := s.db.ExecContext(ctx,
		fmt.Sprintf("DELETE FROM %s WHERE created_at < %s", s.table, ph[0]),
		before.UTC().Format(time.RFC3339Nano))
	if err != nil {
		return 0, fmt.Errorf("admin audit: purge: %w", err)
	}
	dropped, err := res.RowsAffected()
	if err != nil {
		// A driver that does not report it purged anyway; the count is
		// cosmetic, the deletion is not.
		return 0, nil
	}
	_, _ = s.fallback.purge(before)
	return int(dropped), nil
}
