package admin

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/jcsvwinston/nucleus/pkg/auth"
)

// BootstrapAdminConfig defines how the framework should initialize the first
// admin account when the admin users table is empty.
type BootstrapAdminConfig struct {
	Username string
	Email    string
	Password string

	// System is the database dialect of the target connection, as
	// reported by `db.DB.System()` ("sqlite", "postgresql", "mysql",
	// "mssql", "oracle"). It selects the dialect-appropriate
	// CREATE-TABLE form for the admin users table. An empty System
	// falls back to the portable `CREATE TABLE IF NOT EXISTS` form
	// (accepted by SQLite, PostgreSQL, and MySQL) — preserving the
	// pre-dialect-aware behaviour for any caller that does not set it.
	System string
}

// BootstrapAdminResult reports whether a bootstrap admin account was created.
// Password is only populated when generated by the framework.
type BootstrapAdminResult struct {
	Created           bool
	Username          string
	Password          string
	PasswordGenerated bool
}

// EnsureBootstrapAdminUser guarantees the admin users table exists and creates
// one default superuser if the table is currently empty.
func EnsureBootstrapAdminUser(ctx context.Context, sqlDB *sql.DB, cfg BootstrapAdminConfig) (BootstrapAdminResult, error) {
	if sqlDB == nil {
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap: nil sql db")
	}
	if ctx == nil {
		ctx = context.Background()
	}

	username := strings.TrimSpace(cfg.Username)
	if username == "" {
		username = "admin"
	}
	email := strings.TrimSpace(cfg.Email)
	if email == "" {
		email = "admin@localhost"
	}
	password := strings.TrimSpace(cfg.Password)
	passwordGenerated := false
	if password == "" {
		password = newBootstrapAdminPassword()
		passwordGenerated = true
	}
	if len(password) < 8 {
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap password must be at least 8 characters")
	}

	if err := ensureBootstrapAdminUsersTable(ctx, sqlDB, cfg.System); err != nil {
		return BootstrapAdminResult{}, err
	}

	count, err := countBootstrapAdminUsers(ctx, sqlDB)
	if err != nil {
		return BootstrapAdminResult{}, err
	}
	if count > 0 {
		return BootstrapAdminResult{
			Created:           false,
			Username:          username,
			PasswordGenerated: false,
		}, nil
	}

	hash, err := auth.HashPassword(password)
	if err != nil {
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap hash password: %w", err)
	}

	userID := newBootstrapAdminUserID()
	now := time.Now().UTC().Format(time.RFC3339)
	if err := insertBootstrapAdminUser(ctx, sqlDB, cfg.System, bootstrapAdminRow{
		id:           userID,
		username:     username,
		email:        email,
		passwordHash: hash,
		isSuperuser:  1,
		createdAt:    now,
		updatedAt:    now,
	}); err != nil {
		if isBootstrapDuplicateError(err) {
			return BootstrapAdminResult{
				Created:           false,
				Username:          username,
				PasswordGenerated: false,
			}, nil
		}
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap insert user: %w", err)
	}

	result := BootstrapAdminResult{
		Created:           true,
		Username:          username,
		PasswordGenerated: passwordGenerated,
	}
	if passwordGenerated {
		result.Password = password
	}
	return result, nil
}

func ensureBootstrapAdminUsersTable(ctx context.Context, sqlDB *sql.DB, system string) error {
	query := bootstrapAdminUsersTableDDL(system)
	if _, err := sqlDB.ExecContext(ctx, query); err != nil {
		return fmt.Errorf("admin bootstrap ensure users table: %w", err)
	}
	return nil
}

// bootstrapAdminUsersTableDDL returns the CREATE-TABLE statement for the
// admin users table in the dialect of the given system. It mirrors the
// dialect discipline of pkg/db's migrationsTableDDL / checksumsTableDDL:
//
//   - mssql: SQL Server has no `CREATE TABLE IF NOT EXISTS`; the table
//     is guarded with `IF OBJECT_ID(...) IS NULL`. Booleans map to
//     `BIT`, unbounded text to `NVARCHAR(MAX)`, bounded strings to
//     `NVARCHAR(n)`.
//   - oracle: Oracle has no `CREATE TABLE IF NOT EXISTS`; the create is
//     wrapped in a PL/SQL block that swallows ORA-00955 ("name already
//     used"). Booleans map to `NUMBER(1)`, strings to `VARCHAR2(n)`.
//     Critically, the column-constraint order is `DEFAULT <v> NOT NULL`
//     (Oracle rejects `NOT NULL DEFAULT <v>` with ORA-03076 — the bug
//     this function fixes).
//   - default (sqlite / postgresql / mysql, and the empty-system
//     fallback): the portable `CREATE TABLE IF NOT EXISTS` form,
//     unchanged from the pre-dialect-aware implementation.
//
// The COUNT statement elsewhere in this file is dialect-agnostic (it
// binds no values). The INSERT is dialect-aware too: it binds its values
// with dialect-appropriate placeholders when System is known
// (insertBootstrapAdminUser / bootstrapInsertPlaceholders), falling back
// to inline literals only when the dialect is unknown.
func bootstrapAdminUsersTableDDL(system string) string {
	switch system {
	case "mssql":
		return fmt.Sprintf(`IF OBJECT_ID('%s', 'U') IS NULL
	CREATE TABLE %s (
		id NVARCHAR(64) NOT NULL PRIMARY KEY,
		username NVARCHAR(191) NOT NULL UNIQUE,
		email NVARCHAR(191) NOT NULL UNIQUE,
		password_hash NVARCHAR(MAX) NOT NULL,
		is_superuser BIT NOT NULL DEFAULT 0,
		created_at NVARCHAR(64) NOT NULL,
		updated_at NVARCHAR(64) NOT NULL
	)`, defaultAdminUsersTable, defaultAdminUsersTable)
	case "oracle":
		return fmt.Sprintf(`BEGIN
	EXECUTE IMMEDIATE 'CREATE TABLE %s (
		id VARCHAR2(64) NOT NULL PRIMARY KEY,
		username VARCHAR2(191) NOT NULL UNIQUE,
		email VARCHAR2(191) NOT NULL UNIQUE,
		password_hash VARCHAR2(4000) NOT NULL,
		is_superuser NUMBER(1) DEFAULT 0 NOT NULL,
		created_at VARCHAR2(64) NOT NULL,
		updated_at VARCHAR2(64) NOT NULL
	)';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -955 THEN RAISE; END IF;
END;`, defaultAdminUsersTable)
	default:
		return fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s (
	id VARCHAR(64) PRIMARY KEY,
	username VARCHAR(191) NOT NULL UNIQUE,
	email VARCHAR(191) NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	is_superuser INTEGER NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
)`, defaultAdminUsersTable)
	}
}

// bootstrapAdminRow is the fixed set of values written by the admin
// bootstrap INSERT, in column order.
type bootstrapAdminRow struct {
	id           string
	username     string
	email        string
	passwordHash string
	isSuperuser  int
	createdAt    string
	updatedAt    string
}

// adminUsersInsertColumns is the column list (and, with it, the value
// count) for the bootstrap admin INSERT.
const adminUsersInsertColumns = "(id, username, email, password_hash, is_superuser, created_at, updated_at)"

// insertBootstrapAdminUser inserts the first admin user. When system names
// a known dialect the values are bound as parameters (no SQL-string
// concatenation); when system is empty or unrecognised the dialect — and
// therefore the placeholder style — is unknown, so it falls back to the
// portable inline-literal form. Real deployments always pass System
// (orbit.go derives it from db.DB.System()); the inline path exists only
// for a caller that opts out of dialect awareness, and its values are
// operator config / framework-generated (never end-user input), with
// single quotes doubled.
func insertBootstrapAdminUser(ctx context.Context, sqlDB *sql.DB, system string, row bootstrapAdminRow) error {
	if ph := bootstrapInsertPlaceholders(system); ph != nil {
		stmt := fmt.Sprintf("INSERT INTO %s %s VALUES (%s)",
			defaultAdminUsersTable, adminUsersInsertColumns, strings.Join(ph, ", "))
		_, err := sqlDB.ExecContext(ctx, stmt,
			row.id, row.username, row.email, row.passwordHash, row.isSuperuser, row.createdAt, row.updatedAt)
		return err
	}

	stmt := fmt.Sprintf("INSERT INTO %s %s VALUES (%s, %s, %s, %s, %d, %s, %s)",
		defaultAdminUsersTable, adminUsersInsertColumns,
		quoteBootstrapSQLString(row.id),
		quoteBootstrapSQLString(row.username),
		quoteBootstrapSQLString(row.email),
		quoteBootstrapSQLString(row.passwordHash),
		row.isSuperuser,
		quoteBootstrapSQLString(row.createdAt),
		quoteBootstrapSQLString(row.updatedAt),
	)
	_, err := sqlDB.ExecContext(ctx, stmt)
	return err
}

// bootstrapInsertPlaceholders returns the positional bind placeholders for
// the admin-users INSERT in the dialect of system, matching the styles
// pkg/db uses (schema_drift.go): "?" for sqlite/mysql, "$N" for
// postgresql, "@pN" for mssql, ":N" for oracle. It returns nil for an
// empty or unrecognised system, signalling the caller to use the portable
// inline-literal fallback (no portable placeholder style exists).
func bootstrapInsertPlaceholders(system string) []string {
	const n = 7 // len(adminUsersInsertColumns) values
	switch system {
	case "sqlite", "mysql":
		ph := make([]string, n)
		for i := range ph {
			ph[i] = "?"
		}
		return ph
	case "postgresql":
		return numberedBindPlaceholders("$", n)
	case "mssql":
		return numberedBindPlaceholders("@p", n)
	case "oracle":
		return numberedBindPlaceholders(":", n)
	default:
		return nil
	}
}

func numberedBindPlaceholders(prefix string, n int) []string {
	ph := make([]string, n)
	for i := range ph {
		ph[i] = prefix + strconv.Itoa(i+1)
	}
	return ph
}

func countBootstrapAdminUsers(ctx context.Context, sqlDB *sql.DB) (int, error) {
	var count int
	query := fmt.Sprintf("SELECT COUNT(*) FROM %s", defaultAdminUsersTable)
	if err := sqlDB.QueryRowContext(ctx, query).Scan(&count); err != nil {
		return 0, fmt.Errorf("admin bootstrap count users: %w", err)
	}
	return count, nil
}

func newBootstrapAdminPassword() string {
	buf := make([]byte, 14)
	if _, err := rand.Read(buf); err != nil {
		return fmt.Sprintf("nucleus-%d", time.Now().UnixNano())
	}
	return "nucleus-" + hex.EncodeToString(buf)
}

func newBootstrapAdminUserID() string {
	buf := make([]byte, 6)
	if _, err := rand.Read(buf); err != nil {
		return fmt.Sprintf("u_%d", time.Now().UnixNano())
	}
	return "u_" + time.Now().UTC().Format("20060102150405") + "_" + hex.EncodeToString(buf)
}

func quoteBootstrapSQLString(raw string) string {
	return "'" + strings.ReplaceAll(raw, "'", "''") + "'"
}

func isBootstrapDuplicateError(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	if strings.Contains(msg, "unique constraint") {
		return true
	}
	if strings.Contains(msg, "duplicate key") {
		return true
	}
	if strings.Contains(msg, "duplicate entry") {
		return true
	}
	if strings.Contains(msg, "violates unique") {
		return true
	}
	return false
}
