package admin

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"fmt"
	"strings"
	"time"

	"github.com/jcsvwinston/nucleus/pkg/auth"
)

// BootstrapAdminConfig defines how the framework should initialize the first
// admin account when the admin users table is empty.
type BootstrapAdminConfig struct {
	Username string
	Email    string
	Password string

	// System is the database dialect of the target connection, as
	// reported by `db.DB.System()` ("sqlite", "postgresql", "mysql",
	// "mssql", "oracle"). It selects the dialect-appropriate
	// CREATE-TABLE form for the admin users table. An empty System
	// falls back to the portable `CREATE TABLE IF NOT EXISTS` form
	// (accepted by SQLite, PostgreSQL, and MySQL) — preserving the
	// pre-dialect-aware behaviour for any caller that does not set it.
	System string
}

// BootstrapAdminResult reports whether a bootstrap admin account was created.
// Password is only populated when generated by the framework.
type BootstrapAdminResult struct {
	Created           bool
	Username          string
	Password          string
	PasswordGenerated bool
}

// EnsureBootstrapAdminUser guarantees the admin users table exists and creates
// one default superuser if the table is currently empty.
func EnsureBootstrapAdminUser(ctx context.Context, sqlDB *sql.DB, cfg BootstrapAdminConfig) (BootstrapAdminResult, error) {
	if sqlDB == nil {
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap: nil sql db")
	}
	if ctx == nil {
		ctx = context.Background()
	}

	username := strings.TrimSpace(cfg.Username)
	if username == "" {
		username = "admin"
	}
	email := strings.TrimSpace(cfg.Email)
	if email == "" {
		email = "admin@localhost"
	}
	password := strings.TrimSpace(cfg.Password)
	passwordGenerated := false
	if password == "" {
		password = newBootstrapAdminPassword()
		passwordGenerated = true
	}
	if len(password) < 8 {
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap password must be at least 8 characters")
	}

	if err := ensureBootstrapAdminUsersTable(ctx, sqlDB, cfg.System); err != nil {
		return BootstrapAdminResult{}, err
	}

	count, err := countBootstrapAdminUsers(ctx, sqlDB)
	if err != nil {
		return BootstrapAdminResult{}, err
	}
	if count > 0 {
		return BootstrapAdminResult{
			Created:           false,
			Username:          username,
			PasswordGenerated: false,
		}, nil
	}

	hash, err := auth.HashPassword(password)
	if err != nil {
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap hash password: %w", err)
	}

	userID := newBootstrapAdminUserID()
	now := time.Now().UTC().Format(time.RFC3339)
	insert := fmt.Sprintf(
		"INSERT INTO %s (id, username, email, password_hash, is_superuser, created_at, updated_at) VALUES (%s, %s, %s, %s, %d, %s, %s)",
		defaultAdminUsersTable,
		quoteBootstrapSQLString(userID),
		quoteBootstrapSQLString(username),
		quoteBootstrapSQLString(email),
		quoteBootstrapSQLString(hash),
		1,
		quoteBootstrapSQLString(now),
		quoteBootstrapSQLString(now),
	)
	if _, err := sqlDB.ExecContext(ctx, insert); err != nil {
		if isBootstrapDuplicateError(err) {
			return BootstrapAdminResult{
				Created:           false,
				Username:          username,
				PasswordGenerated: false,
			}, nil
		}
		return BootstrapAdminResult{}, fmt.Errorf("admin bootstrap insert user: %w", err)
	}

	result := BootstrapAdminResult{
		Created:           true,
		Username:          username,
		PasswordGenerated: passwordGenerated,
	}
	if passwordGenerated {
		result.Password = password
	}
	return result, nil
}

func ensureBootstrapAdminUsersTable(ctx context.Context, sqlDB *sql.DB, system string) error {
	query := bootstrapAdminUsersTableDDL(system)
	if _, err := sqlDB.ExecContext(ctx, query); err != nil {
		return fmt.Errorf("admin bootstrap ensure users table: %w", err)
	}
	return nil
}

// bootstrapAdminUsersTableDDL returns the CREATE-TABLE statement for the
// admin users table in the dialect of the given system. It mirrors the
// dialect discipline of pkg/db's migrationsTableDDL / checksumsTableDDL:
//
//   - mssql: SQL Server has no `CREATE TABLE IF NOT EXISTS`; the table
//     is guarded with `IF OBJECT_ID(...) IS NULL`. Booleans map to
//     `BIT`, unbounded text to `NVARCHAR(MAX)`, bounded strings to
//     `NVARCHAR(n)`.
//   - oracle: Oracle has no `CREATE TABLE IF NOT EXISTS`; the create is
//     wrapped in a PL/SQL block that swallows ORA-00955 ("name already
//     used"). Booleans map to `NUMBER(1)`, strings to `VARCHAR2(n)`.
//     Critically, the column-constraint order is `DEFAULT <v> NOT NULL`
//     (Oracle rejects `NOT NULL DEFAULT <v>` with ORA-03076 — the bug
//     this function fixes).
//   - default (sqlite / postgresql / mysql, and the empty-system
//     fallback): the portable `CREATE TABLE IF NOT EXISTS` form,
//     unchanged from the pre-dialect-aware implementation.
//
// The INSERT and COUNT statements elsewhere in this file are already
// dialect-agnostic (standard SQL string literals, no placeholders), so
// the CREATE statement is the only dialect-specific surface.
func bootstrapAdminUsersTableDDL(system string) string {
	switch system {
	case "mssql":
		return fmt.Sprintf(`IF OBJECT_ID('%s', 'U') IS NULL
	CREATE TABLE %s (
		id NVARCHAR(64) NOT NULL PRIMARY KEY,
		username NVARCHAR(191) NOT NULL UNIQUE,
		email NVARCHAR(191) NOT NULL UNIQUE,
		password_hash NVARCHAR(MAX) NOT NULL,
		is_superuser BIT NOT NULL DEFAULT 0,
		created_at NVARCHAR(64) NOT NULL,
		updated_at NVARCHAR(64) NOT NULL
	)`, defaultAdminUsersTable, defaultAdminUsersTable)
	case "oracle":
		return fmt.Sprintf(`BEGIN
	EXECUTE IMMEDIATE 'CREATE TABLE %s (
		id VARCHAR2(64) NOT NULL PRIMARY KEY,
		username VARCHAR2(191) NOT NULL UNIQUE,
		email VARCHAR2(191) NOT NULL UNIQUE,
		password_hash VARCHAR2(4000) NOT NULL,
		is_superuser NUMBER(1) DEFAULT 0 NOT NULL,
		created_at VARCHAR2(64) NOT NULL,
		updated_at VARCHAR2(64) NOT NULL
	)';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -955 THEN RAISE; END IF;
END;`, defaultAdminUsersTable)
	default:
		return fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s (
	id VARCHAR(64) PRIMARY KEY,
	username VARCHAR(191) NOT NULL UNIQUE,
	email VARCHAR(191) NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	is_superuser INTEGER NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
)`, defaultAdminUsersTable)
	}
}

func countBootstrapAdminUsers(ctx context.Context, sqlDB *sql.DB) (int, error) {
	var count int
	query := fmt.Sprintf("SELECT COUNT(*) FROM %s", defaultAdminUsersTable)
	if err := sqlDB.QueryRowContext(ctx, query).Scan(&count); err != nil {
		return 0, fmt.Errorf("admin bootstrap count users: %w", err)
	}
	return count, nil
}

func newBootstrapAdminPassword() string {
	buf := make([]byte, 14)
	if _, err := rand.Read(buf); err != nil {
		return fmt.Sprintf("nucleus-%d", time.Now().UnixNano())
	}
	return "nucleus-" + hex.EncodeToString(buf)
}

func newBootstrapAdminUserID() string {
	buf := make([]byte, 6)
	if _, err := rand.Read(buf); err != nil {
		return fmt.Sprintf("u_%d", time.Now().UnixNano())
	}
	return "u_" + time.Now().UTC().Format("20060102150405") + "_" + hex.EncodeToString(buf)
}

func quoteBootstrapSQLString(raw string) string {
	return "'" + strings.ReplaceAll(raw, "'", "''") + "'"
}

func isBootstrapDuplicateError(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	if strings.Contains(msg, "unique constraint") {
		return true
	}
	if strings.Contains(msg, "duplicate key") {
		return true
	}
	if strings.Contains(msg, "duplicate entry") {
		return true
	}
	if strings.Contains(msg, "violates unique") {
		return true
	}
	return false
}
